title:  "Dianne Blogs"
tagline: "Welcome To My Life"
description:
author:
  name: "Dianne"
  twitter: dianneblogs

# Change to true for Disqus comments
disqus:
  comments: true
  disqus_shortname: 'dianneblogs'

menu:
- {name: 'About', file: 'about.html'}
- {name: 'Faith', file: 'faith.html'}
- {name: 'College', file: 'college.html'}
- {name: 'All Things Life', file: 'lifestyle.html'}
- {name: 'Travel', file: 'travel.html'}

social:
- {icon: 'twitter', link: 'https://twitter.com/dianneblogs'}
- {icon: 'instagram', link: 'https://instagram.com/dianneblogs'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
