title:  "Home"
tagline: "Welcome To My Life"
description:
author:
  name: "Dianne"
  twitter: dianneblogs

# Change to true for Disqus comments
disqus:
  comments: true
  disqus_shortname: 'www-dianneblogs-com'

# Google Tracking
google-ID: 'UA-108973438-1'



menu:
- {name: 'Blog',  file: 'blog.html'}
- {name: 'Faith', file: 'faith.html'}
- {name: 'College', file: 'college.html'}
- {name: 'All Things Life', file: 'lifestyle.html'}
- {name: 'Travel', file: 'travel.html'}

social:
- {icon: 'twitter', link: 'https://twitter.com/dianneblogs'}
- {icon: 'instagram', link: 'https://instagram.com/dianneblogs'}
- {icon: 'pinterest', link: 'https://www.pinterest.com/dianneblogs/pins/'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
